# Generated by Django 5.1.1 on 2024-12-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Имя')),
                ('surname', models.TextField(blank=True, db_column='Фамилия')),
                ('grand_name', models.TextField(blank=True, db_column='Отчество')),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Rieltor',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Имя')),
                ('surname', models.TextField(blank=True, db_column='Фамилия')),
                ('grand_name', models.TextField(blank=True, db_column='Отчество')),
                ('fee_rate', models.IntegerField(blank=True, db_column='Доля')),
            ],
            options={
                'db_table': 'Rieltor',
            },
        ),
    ]
