# Generated by Django 5.1.1 on 2024-12-20 23:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esoft', '0003_alter_client_email_alter_client_grand_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('square', models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('floor', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('rooms_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True)),
                ('square', models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('floors_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True)),
                ('rooms_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True)),
                ('square', models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RentalObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coordinate_x', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('coordinate_y', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esoft.city')),
                ('flat', models.ForeignKey(blank=True, db_column='Квартира', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='esoft.flat')),
                ('house', models.ForeignKey(blank=True, db_column='Дом', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='esoft.house')),
                ('street', models.ForeignKey(blank=True, db_column='Улица', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='esoft.street')),
            ],
            options={
                'db_table': 'RentalObject',
            },
        ),
    ]
