# Generated by Django 5.1.1 on 2024-12-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esoft', '0004_city_field_flat_house_street_rentalobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalobject',
            name='city',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.RemoveField(
            model_name='rentalobject',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='rentalobject',
            name='house',
        ),
        migrations.RemoveField(
            model_name='rentalobject',
            name='street',
        ),
        migrations.AddField(
            model_name='rentalobject',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentalobject',
            name='field_square',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True),
        ),
        migrations.AddField(
            model_name='rentalobject',
            name='flat_floor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='rentalobject',
            name='flat_rooms_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True),
        ),
        migrations.AddField(
            model_name='rentalobject',
            name='flat_square',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True),
        ),
        migrations.AddField(
            model_name='rentalobject',
            name='house_floors_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True),
        ),
        migrations.AddField(
            model_name='rentalobject',
            name='house_rooms_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True),
        ),
        migrations.AddField(
            model_name='rentalobject',
            name='house_square',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True),
        ),
        migrations.AddField(
            model_name='rentalobject',
            name='street_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Flat',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
    ]
